version: 2
updates:

# Maintain dependencies for Ruby
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"

# Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
