title: MTG Baselland
email: mtgbearsocialmedia@gmail.com
description: >-
  Magic: The Gathering in Liestal
tagline: >-
  Magic: The Gathering in Liestal
logo: /assets/img/logo.png
baseurl: ""
url: "https://mtgbl.ch" # the base hostname & protocol for your site
timezone: UTC
future: true  # render events and posts with a date in the future
lang: de

author:
  name: MTG Baselland
  email: mtgbearsocialmedia@gmail.com

social:
  name: MTG Baselland
  links:
    - https://www.facebook.com/mtgbaselland/
    - https://chat.whatsapp.com/HQ7IINFrZB63esDNRqsIUw
    - https://github.com/mtgbl

locale: de_CH

header_pages:
  - about.markdown
  - events.markdown
  - liga/overview.markdown
  - bears.markdown

collections:
  events:
    sort_by: date
    output: true
  locations:
    output: true

#theme: minima
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - icon: whatsapp
      url: "https://chat.whatsapp.com/HQ7IINFrZB63esDNRqsIUw"
      title: "Unsere WhatsApp-Gruppe"
    - icon: facebook
      url: "https://www.facebook.com/mtgbaselland/"
      title: "Unsere Facebook-Gruppe"
    - icon: calendar
      fa_namespace: regular
      url: "/events.ics"
      title: "Event-Kalender"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-spaceship
  - jekyll-toc
  - jekyll-redirect-from

strict_front_matter: true
liquid:
  error_mode: strict
#  strict_variables: true
  strict_filters: true

jekyll-spaceship:
  processors:
    - table-processor

maps_api_key: AIzaSyCsr4EVNw-s-VDiSyJyXamPbTRVzJrycGg

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /neuigkeiten/:path
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
      permalink: /event/:path
  - scope:
      path: ""
      type: "locations"
    values:
      layout: "location"
      permalink: /standort/:path
  - scope:
      path: "assets/img"
    values:
      image: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - README.md
  - .github/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _drafts/
