# MTGBL Website
Static page generated by Jekyll.

## Requirements
- ruby >=3.2
- gem >=3.4

## Installation
```sh
bundle install
```
## Build
```sh
bundle exec jekyll build
```

## Run locally
```sh
bundle exec jekyll serve
```
Visit at http://127.0.0.1:4000/
